#!/usr/bin/env bash
# Transfers a file from client to server

path_to_file=$1
ip_address=$2
username=$3
path_to_ssh_key=$4

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 3 ]; then
	scp -o StrictHostKeyChecking=no $path_to_file "$username@$ip_address":~/
else
	scp -i $path_to_ssh_key -o StrictHostKeyChecking=no $path_to_file "$username@$ip_address":~/
fi
