#!/usr/bin/env bash
# installs an nginx web server

sudo apt-get update;
sudo apt-get -y nginx;
ufw allow 'Nginx HTTP'
sudo echo "<!Doctype html> <html> <body> <p>Hello World!</p> </body> </html>" > /var/www/html/index.html
service nginx start
