#!/usr/bin/env bash
# installs an nginx web server

sudo apt-get -y nginx;
sudo rm /var/www/html/index.nginx-debian.html;
sudo echo "<!Doctype html> <html> <body> <p>Hello World!</p> </body> </html>" >> /var/www/html/hello.html
