#!/usr/bin/env bash
# Script to install Nginx and set up a redirect using the `return` directive

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

redirect_line="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtu.be/dQw4w9WgXcQ?si=SvyXNjm9-aohAC6r;\n\t}"
sudo sed -i "/server_name _;/ a $redirect_line" /etc/nginx/sites-enabled/default

sudo service nginx restart
