#!/usr/bin/env bash
# Redirects /redirect_me to another page

sudo apt-get update;
sudo apt-get -y nginx;

echo "Hello World!" > /var/www/html/index.html
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtu.be/dQw4w9WgXcQ?si=SvyXNjm9-aohAC6r permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
