#!/usr/bin/env bash
# creates a custom 404 not found page

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtu.be/dQw4w9WgXcQ?si=SvyXNjm9-aohAC6r permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default


echo "Ceci n'est pas une page" > /var/www/html/404.html
string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
