#!/usr/bin/bash env
# configures nginx on a brand new ubuntu server

sudo apt-get update

sudo apt-get -y install nginx

sudo ufw allow 'NGINX HTTP'

sudo mkdir -P /var/www/html

sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

header="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https://www.youtube.com permanent"
sudo sed -i "s/server_name _;/$header/" /etc/nginx/sites-enabled/default

error="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$error/" /etc/nginx/sites-enabled/default

sudo service nginx restart
