#!/usr/bin/env bash
# Installs and sets up a load balancer

sudo apt-get update

sudo apt-get -y install haproxy

server_config=\
"
frontend  http_front
        bind *:80
        mode http
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 139945-web-01 100.26.252.22 check
        server 139945-web-02 18.209.224.247 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
