#!/usr/bin/env bash
#A script that prints "To infinity and beyond" indefinitely and "I am invincible when receiving a SIGTERM signal


trap 'echo "I am invincible!!!"'  SIGTERM

while true ; do
	echo "To infinty and beyond"
	sleep 2
done
