#!/usr/bin/env bash
#before running the script, localhost resolves to 127.0.0.1 and facebook.com resolves to 157.240.11.35
#after running the script, localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

cp /etc/hosts ~/hosts.new

echo "$localhost_ip	localhost" > ~/hosts.new
echo "$facebook_ip	facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
