#!/usr/bin/env bash
#before running the script, localhost resolves to 127.0.0.1 and facebook.com resolves to 157.240.11.35
#after running the script, localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

sed -i 's/127.0.0.1/127.0.0.2' /etc/hosts
sed -i 's/157.240.11.35/8.8.8.8' /etc/hosts
